context: onprem-omni
contexts:
    onprem-omni:
        endpoints:
            - https://omni.laskonet.com/
        auth:
            siderov1:
                identity: ken.lasko@gmail.com
        cluster: home
